name: 'Create Jira'
description: 'Creates a new Jira issue in Labelbox Jira account'
author: 'Labelbox'
inputs:
  host:
    description: 'The Jira host'
    required: true
  project:
    description: 'The project where the issue should be created'
    required: true
  story-points:
    description: 'The number of story points the issue should have'
    required: true
outputs:
  url:
    description: 'The url of the Jira that was created'

runs:
  using: 'node12'
  main: 'dist/index.js'
